version: '3.9'
services:
  frontend:
    build: ./src/frontend
    environment:
      - NODE_ENV=development
    volumes:
      - ./src/frontend:/workspace/frontend
    ports:
      - 8080:8080
    command: sleep infinity

  backend:
    build: ./src/backend
    volumes:
      - ./src/backend:/workspace/backend
    ports:
      - 8081:8081
    command: sleep infinity